# CO2 DATA RETRIEVAL FROM MULTIPLE SOURCES
## TABLE OF CONTENTS
1. NOAA - Moana Loa
2. SCRIPPS: ICECORE Dataset (1600-Present)
3. SCRIPPS: Substation Sampling Data from Worldwide Locations

_Required Citations_: 
* **II**. Macfarling Meure, C. et al., 2006: Law Dome CO2, CH4 and N2O ice core records extended to 2000 years BP. Geophysical Research Letters, 33.
* **III**. C. D. Keeling, S. C. Piper, R. B. Bacastow, M. Wahlen, T. P. Whorf, M. Heimann, and H. A. Meijer, Exchanges of atmospheric CO2 and 13CO2 with the terrestrial biosphere and oceans from 1978 to 2000. I. Global aspects, SIO Reference Series, No. 01-06, Scripps Institution of Oceanography, San Diego, 88 pages, 2001"



In [20]:
import pandas as pd
import numpy as np

#Retrieving from NOAA: Moana Loa database
df_moanaloa = pd.read_csv('ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt', 
                 comment = '#',delimiter='   ', header=None)
df_moanaloa = df_moanaloa.rename(index=str, columns={0: "Date", 1: "Mean_CO2", 2:'StdDev'})
print(df_moanaloa.head())




   Date  Mean_CO2  StdDev
0  1959    315.97    0.12
1  1960    316.91    0.12
2  1961    317.64    0.12
3  1962    318.45    0.12
4  1963    318.99    0.12


/Users/rahulbirmiwal/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


## CO2 DATA FROM SCRIPPS: ICECORE HISTORICAL DATASET (1600-PRESENT)

In [21]:


#Retrieving from Scripps ICE-CORE 13CE-present dataset
df_icecore = pd.read_csv('http://scrippsco2.ucsd.edu/assets/data/atmospheric/merged_ice_core_mlo_spo/spline_merged_ice_core_yearly.csv',
                         comment = '"',delimiter=',',header=None)
df_icecore = df_icecore.rename(index = str, columns={0:'Date',1:"Mean_CO2"})
print("################ DATA FROM SCRIPPS: IceCore DATA 1600-Present #############")
print(df_icecore.head())

################ DATA FROM SCRIPPS: IceCore DATA 1600-Present #############
   Date  Mean_CO2
0  1679   275.903
1  1680   275.937
2  1681   275.972
3  1682   276.007
4  1683   276.042


## CO2 DATA FROM SCRIPPS STATION SAMPLING WORLDWIDE

In [24]:


print("####################################################################")
print("## FOLLOWING DATA SETS FROM SCRIPPS:STATION DATA FROM WORLDWIDE LOCATIONS")


#Retrieving from Scripps ALERT NWT, CANADA Station Data
df_alertNWT = pd.read_csv('http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_co2/monthly/monthly_flask_co2_alt.csv',
                          comment = '"', delimiter=",",header=None)
print("################ DATA FROM SCRIPPS: ALERT, NWT, CANADA CO2 DATA #############")
print(df_alertNWT.head())


#Retrieving from Scripps LA JOLLA, CA, UNITED STATES  Station Data
df_lajolla = pd.read_csv('http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_co2/monthly/monthly_flask_co2_ljo.csv',
                          comment = '"', delimiter=",",header=None)
print("################ DATA FROM SCRIPPS: LA JOLLA, CA, UNITED STATES CO2 DATA #############")
print(df_lajolla.head())


#Retrieving from Scripps CHRISTMAS ISLAND, AUSTRALIA  Station Data
df_christmas_isl = pd.read_csv('http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_isotopic/monthly/monthly_flask_c13_chr.csv', 
                                comment = '"',delimiter=",",header=None)
print("################ DATA FROM SCRIPPS: CHRISTMAS ISLAND, AUSTRALIA CO2 DATA #############")
print(df_christmas_isl.head())

#Retrieving from Scripps AMERICAN SAMOA Station Data
df_am_samoa = pd.read_csv('http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_co2/monthly/monthly_flask_co2_sam.csv', 
                                comment = '"',delimiter=",",header=None)
print("################ DATA FROM SCRIPPS: AMERICAN SAMOA CO2 DATA #############")
print(df_am_samoa.head())

#Retrieving from Scripps SOUTH POLE Station Data
df_southpole = pd.read_csv('http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/merged_in_situ_and_flask/monthly/monthly_merge_co2_spo.csv',
                            comment = '"',delimiter=",",header=None)
print("################ DATA FROM SCRIPPS: SOUTH POLE, ANTARCTICA CO2 DATA #############")
print(df_southpole.head())

####################################################################
## FOLLOWING DATA SETS FROM SCRIPPS:STATION DATA FROM WORLDWIDE LOCATIONS
################ DATA FROM SCRIPPS: ALERT, NWT, CANADA CO2 DATA #############
      0    1         2           3          4           5            6  \
0    Yr   Mn      Date        Date        CO2  seasonally          fit   
1                                                adjusted                
2                Excel                  [ppm]      [ppm]         [ppm]   
3  1985   01     31062   1985.0411     -99.99      -99.99       -99.99   
4  1985   02     31093   1985.1260     -99.99      -99.99       -99.99   

              7             8                9  
0    seasonally           CO2       seasonally  
1  adjusted fit        filled  adjusted filled  
2         [ppm]         [ppm]            [ppm]  
3        -99.99        -99.99           -99.99  
4        -99.99        -99.99           -99.99  
################ DATA FROM SCRIPPS: LA J

## Create a function to do all of the above....

In [36]:
def grab_scripps_co2_data():
    links = ['http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_co2/monthly/monthly_flask_co2_alt.csv',
            'http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_co2/monthly/monthly_flask_co2_ljo.csv', 
            'http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_isotopic/monthly/monthly_flask_c13_chr.csv',
            'http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/flask_co2/monthly/monthly_flask_co2_sam.csv',
            'http://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/merged_in_situ_and_flask/monthly/monthly_merge_co2_spo.csv']
    locations = ['Alert_CAN','LaJolla_USA','ChristmasIsland_AUS','AmericanSamoa_ASM','SouthPole_ANT']
    master_df = pd.DataFrame()
    count = 0
    for link in links: 
        station_df = pd.read_csv(link,comment = '"',delimiter=",",header=None)
        print(station_df.columns.values)
        #Add column denoting _this_ substation location 
        station_df['Location'] = locations[count]
        count += 1
        
        #only get the columns we care about...
        station_df = station_df.iloc[:,[0,3,4,10]]
        print(station_df.columns.values)
        master_df = master_df.append(station_df)
    print(master_df.head())
grab_scripps_co2_data()

[0 1 2 3 4 5 6 7 8 9]
[0 3 4 'Location']
[0 1 2 3 4 5 6 7 8 9]
[0 3 4 'Location']
[0 1 2 3 4 5 6 7 8 9]
[0 3 4 'Location']
[0 1 2 3 4 5 6 7 8 9]
[0 3 4 'Location']
[0 1 2 3 4 5 6 7 8 9]
[0 3 4 'Location']
      0           3          4   Location
0    Yr        Date        CO2  Alert_CAN
1                               Alert_CAN
2                        [ppm]  Alert_CAN
3  1985   1985.0411     -99.99  Alert_CAN
4  1985   1985.1260     -99.99  Alert_CAN
